# Generated by Django 4.2.16 on 2024-10-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_thing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(choices=[('Электроника', 'Электроника'), ('Одежда и обувь', 'Одежда и обувь'), ('Мебель', 'Мебель'), ('Книги и журналы', 'Книги и журналы'), ('Детские товары', 'Детские товары'), ('Домашний декор и аксессуары', 'Домашний декор и аксессуары'), ('Спортивные товары', 'Спортивные товары'), ('Инструменты и садовый инвентарь', 'Инструменты и садовый инвентарь'), ('Кухонные принадлежности', 'Кухонные принадлежности'), ('Хобби и развлечения', 'Хобби и развлечения'), ('Товары для домашних животных', 'Товары для домашних животных'), ('Автомобильные товары', 'Автомобильные товары')], max_length=255),
        ),
    ]
