# Generated by Django 4.2.16 on 2024-10-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_thing_image_alter_thing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='category',
            field=models.CharField(choices=[('Электроника', 'Электроника'), ('Одежда и обувь', 'Одежда и обувь'), ('Мебель', 'Мебель'), ('Книги и журналы', 'Книги и журналы'), ('Детские товары', 'Детские товары'), ('Домашний декор и аксессуары', 'Домашний декор и аксессуары'), ('Спортивные товары', 'Спортивные товары'), ('Инструменты и садовый инвентарь', 'Инструменты и садовый инвентарь'), ('Кухонные принадлежности', 'Кухонные принадлежности'), ('Хобби и развлечения', 'Хобби и развлечения'), ('Товары для домашних животных', 'Товары для домашних животных'), ('Автомобильные товары', 'Автомобильные товары')], default='Электроника', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
