# Generated by Django 4.2.16 on 2024-10-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_thing_category_alter_thing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='notes',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
